development:
  adapter: postgresql
  encoding: unicode
  database: slingplan_development
  host: localhost
  pool: 5
  username: rails
  password: rails

test: &test
  adapter: postgresql
  encoding: unicode
  database: slingplan_test
  host: localhost
  pool: 5
  username: rails
  password: rails

cucumber:
  <<: *test

staging:
  adapter: postgresql
  encoding: unicode
  database: slingplan_staging
  host: localhost
  pool: 5
  username: rails
  password: rails

production:
  adapter: postgresql
  encoding: unicode
  database: slingplan_production
  host: localhost
  pool: 5
  username: rails
  password: rails
