common: &common

  google_analytics: <%= ENV['GOOGLE_ANALYTICS'] %>

  stripe:
    secret: <%= ENV['STRIPE_TEST_SECRET'] %>
    publish: <%= ENV['STRIPE_TEST_PUBLISHABLE'] %>

  slack:
    token: <%= ENV['SLACK_TOKEN'] %>
    webhook_url: <%= ENV['SLACK_WEBHOOK_URL'] %>

  s3:
    bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  mandrill:
    user_name: <%= ENV['MANDRILL_USERNAME'] %>
    password: <%= ENV['MANDRILL_APIKEY'] %>

development:
  <<: *common
  secret_key_base: 48392fb0c2dded7d0042a9240dafe53fd07e82bc497ae4480d839bf510e716a6cbfc174404589c5c6c0bf5d141bac371a2362d3b3047a049f5134ac535aaf2bb

test:
  <<: *common
  secret_key_base: a6bf9528db1abf2e49df2b301e7465399f79a3c94660736f6746055d1877f714d5f116e2c51ebc9b995de0f6e7be1f66c525b5f0556c02624dfd5d80738fc435

staging: &staging
  <<: *common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  <<: *common
  <<: *staging

  stripe:
    secret: <%= ENV['STRIPE_LIVE_SECRET'] %>
    publish: <%= ENV['STRIPE_LIVE_PUBLISHABLE'] %>
